### PR TITLE
cnn notebooks + several fixes

### PR DESCRIPTION
**Pull request by glukhove**
updated:
gitignore
random_forest (path to data)
load_data(new approach)

added:
cnn to notebook

### CODE REVIEW

**Review by Catarina-Alves — COMMENTED** [review]
Do you need to upload the files with the results or is it ok to uploaded clean (without results)?

Adittionally, are you now happy with the path to the data? (related to #12)

**Comment by glukhove** [comment]
I believe there should be results. At least I can see them in my notebook. Are you talking about cnn.py?

About path: it was the best I can come up with. There is a general path to data folder and later everything is added to it.

**Comment by Catarina-Alves** [comment]
@glukhove 
Yeah, there are results. I was suggesting not to have the results in the notebooks and have them separately as `html` file. Do you prefer to have them on the notebook? (It is simply harder to see diffs with images).

About the path: If you are happy with that, I am happy too.

**Comment by glukhove** [comment]
About the results: I believe that it will be better to collect them together and present in README file.
But we are still working on those results. So, we can include them into the other PR.

**Review by Catarina-Alves — APPROVED** [review]
I prefer to save the notebooks without any results on them so they are easier to review on GitHub but if you prefer with them, for a small project like this that can be finishing soon, it is ok.

**Pull request merged**
